version: "3.7"

x-app: &app
  build:
    context: ./
    dockerfile: ./Dockerfile
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
    YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
  tmpfs:
    - /tmp
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - db_data:/app/var/lib/mysql
  environment:
    <<: *env
    # RAILS_MASTER_KEY: 6090e9b1243cb4b1c5de6f024327aa76
    DATABASE_NAME_TEST: task_test
    DATABASE_NAME_DEV: task_dev
    DATABASE_USER: root
    DATABASE_PASSWORD: root
    DATABASE_HOST: db
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
    EDITOR: nano
    RAILS_LOG_TO_STDOUT: 1

services:
  cli:
    <<: *backend
    command: /bin/bash

  rails:
    <<: *backend
    command: rails s -b 0.0.0.0
    ports:
      - '3000:3000'

  db:
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
    expose:
      - '3306'
    logging:
      driver: none
    ports:
      - "3306:3306"

  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
      driver: none

volumes:
  db_data:
  bundle:
  redis:
  rails_cache:
  packs:
  node_modules: