default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch('DATABASE_USER', 'root') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'root') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME_TEST'] %>

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
